### ISSUE TITLE
Unable to add block instance on PostgreSQL sites

### ISSUE THREAD

**Issue by mudrd8mz** [studyingroup-com/moodle-block_requestlist#1]
Attempting to add block instance to my PostgreSQL site, I am getting:

Error reading from database
Debug info: ERROR: syntax error at or near "SEPARATOR"
LINE 2: ... GROUP_CONCAT(request.requester SEPARATOR ...
^
SELECT row_number() OVER (ORDER BY request.fullname) n, count(*) AS request_nb,
GROUP_CONCAT(request.requester SEPARATOR ', ') AS requester_list,
request.id AS requestid,
request.fullname,
request.summary,
category.id AS category_id,
category.name AS category_name
FROM m_course_request AS request
INNER JOIN m_course_categories AS category ON request.category = category.id
GROUP BY request.fullname
ORDER BY category.name, request.fullname;
[array (
)]
Error code: dmlreadexception
Stack trace:

    line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 920 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 191 of /blocks/requestlist/block_requestlist.php: call to pgsql_native_moodle_database->get_records_sql()
    line 94 of /blocks/requestlist/block_requestlist.php: call to block_requestlist::_get_request()
    line 341 of /blocks/moodleblock.class.php: call to block_requestlist->get_content()
    line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
    line 3950 of /lib/outputrenderers.php: call to block_manager->region_has_content()
    line 28 of /theme/classic/layout/columns.php: call to core_renderer->blocks()
    line 1374 of /lib/outputrenderers.php: call to include()
    line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 100 of /index.php: call to core_renderer->header()

**Comment by studyingroup-com** [comment]
Yeah, Postgresql... I've dumped this database since web hosting providers make it so $$$ to host...
Anyway, I've commited a fix. I have no idea whether it's working since, as said, I don't have Postgresql myself.

**Comment by mudrd8mz** [comment]
Moodle has a cross-DB policy and in fact, the Moodle core code is expected to run on MSSQL and Oracle too. For plugins, at least MySQL / MariaDB and PostgreSQL (as the two most used ones) compatibility is required.

It is common among Moodle developers to have PostgreSQL installed locally for development and testing purposes. The hosting providers' plan costs are irrelevant. Thank you for understanding.

**Comment by studyingroup-com** [comment]
I know, I know...
so is it working now?

**Comment by mudrd8mz** [comment]
Good question. Does it? :-)

**Comment by studyingroup-com** [comment]
I presume yes, then. Thanks for reporting!
